_BASE: ../OTAM_base.yaml
TASK_TYPE: few_shot_action
TRAIN:
  ENABLE: true
  USE_CLASSIFICATION: true
  USE_CLASSIFICATION_VALUE: 3.0
  DATASET: Ssv2_few_shot
  META_BATCH: true  # meta or not
  NUM_SAMPLES: 1000000
  WAY: 5
  SHOT: 1
  QUERY_PER_CLASS: 3
  MERGE_BEFORE: true
  QUERY_PER_CLASS_TEST: 1
  NUM_TRAIN_TASKS: 10000
  NUM_TEST_TASKS: 10000
  NUM_VAL_TASKS: 400
  VAL_FRE_ITER: 200
  LOG_FREQ: 50
  BATCH_SIZE: 1  # Same with NUM_GPUS
  CLASS_NAME: ['Apply Eye Makeup', 'Archery', 'Baby Crawling', 'Balance Beam', 'Band Marching', 'Baseball Pitch', 'Basketball', 'Basketball Dunk', 'Bench Press', 'Biking', 'Billiards', 'Blow DryHair', 'Body Weight Squats', 'Bowling', 'Boxing Punching Bag', 'Boxing Speed Bag', 'Breast Stroke', 'Brushing Teeth', 'Cricket Bowling', 'Drumming', 'Fencing', 'Field Hockey Penalty', 'Frisbee Catch', 'Front Crawl', 'Haircut', 'Hammering', 'Head Massage', 'Hula Hoop', 'Javelin Throw', 'Juggling Balls', 'Jumping Jack', 'Kayaking', 'Knitting', 'Long Jump', 'Lunges', 'Military Parade', 'Mixing', 'Mopping Floor', 'Nunchucks', 'Parallel Bars', 'Pizza Tossing', 'Playing Cello', 'Playing Dhol', 'Playing Flute', 'Playing Piano', 'Playing Sitar', 'Playing Tabla', 'Playing Violin', 'Pole Vault', 'Pull Ups', 'Push Ups', 'Rafting', 'Rope Climbing', 'Rowing', 'Shaving Beard', 'Skijet', 'Soccer Juggling', 'Soccer Penalty', 'Sumo Wrestling', 'Swing', 'Table Tennis Shot', 'Tai Chi', 'Throw Discus', 'Trampoline Jumping', 'Typing', 'Uneven Bars', 'Walking WithDog', 'Wall Pushups', 'Writing On Board', 'Yo Yo']
  BATCH_SIZE_PER_TASK: 4
  CHECKPOINT_FILE_PATH: ""
  EVAL_PERIOD: 2
  NUM_FOLDS: 1
  WANDB_GROUP: ucf101

AUGMENTATION:
  COLOR_AUG: false
  NO_RANDOM_ERASE: true

VAL:
  CLASS_NAME: ['Apply Lipstick', 'Cricket Shot', 'Hammer Throw', 'Handstand Pushups', 'High Jump', 'Horse Riding', 'Playing Daf', 'Playing Guitar', 'Shotput', 'Skate Boarding']

TEST:
  ENABLE: false
  DATASET: Ssv2_few_shot
  BATCH_SIZE: 4  # Same with NUM_GPUS
  TEST_SET: val
  CLASS_NAME: ['Blowing Candles', 'Clean And Jerk', 'Cliff Diving', 'Cutting in Kitchen', 'Diving', 'Floor Gymnastics', 'Golf Swing', 'Handstand Walking', 'Horse Race', 'Ice Dancing', 'Jump Rope', 'Pommel Horse', 'Punch', 'Rock Climbing Indoor', 'Salsa Spin', 'Skiing', 'Sky Diving', 'Still Rings', 'Surfing', 'Tennis Swing', 'Volleyball Spiking']
  NUM_ENSEMBLE_VIEWS: 1
  SPATIAL_CROPS: cctltr
  AUTOMATIC_MULTI_SCALE_TEST: false
  UPLOAD_CLASSIFIER_RESULTS: true

VAL:
  CLASS_NAME: [
    "Pushing [something] so it spins",
    "Scooping [something] up with [something]",
    "Lifting up one end of [something], then letting it drop down",
    "Pretending or failing to wipe [something] off of [something]",
    "Holding [something] over [something]",
    "Lifting [something] up completely, then letting it drop down",
    "Showing [something] to the camera",
    "Taking [one of many similar things on the table]",
    "Throwing [something] in the air and catching it",
    "Plugging [something] into [something] but pulling it right out as you remove your hand",
    "Pretending to pour [something] out of [something], but [something] is empty",
    "Putting [something] in front of [something]",
  ]
DATA:
  DATA_ROOT_DIR: data/ucf101/videos
  ANNO_DIR: data/ucf101/annotations
  NUM_INPUT_FRAMES: 8
  SAMPLING_RATE: 50
  SAMPLING_UNIFORM: false
  TRAIN_JITTER_SCALES: [256, 256]
  TRAIN_CROP_SIZE: 224 # 84  # 224
  TEST_CROP_SIZE: 224
  MEAN: [0.48145466, 0.4578275, 0.40821073]
  STD: [0.26862954, 0.26130258, 0.27577711]
  TEST_SCALE: 256
  TEST_CENTER_CROP: true
  CLIP_INTERVAL: 8
  FPS: 12
  TARGET_FPS: 12

LOG_PERIOD: 50
SOLVER:
  BASE_LR: 0.00005 
  LR_POLICY: steps_with_relative_lrs
  STEPS_ITER: 4000
  STEPS: [0, 4, 6]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 10
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 1
  WARMUP_START_LR: 0.00001
  OPTIM_METHOD: adam
  DAMPENING: 0.0
  NESTEROV: true
# add bn, use same lr settings as server

VIDEO:
  HEAD:
    NAME: CNN_OTAM_CLIPFSAR  
    BACKBONE_NAME: "ViT-B/16"

  BACKBONE:
    META_ARCH: Identity

NUM_GPUS: 1
OUTPUT_DIR: output/ucf101

debug: False

CHECKPOINT:
  NUM_TO_KEEP: 3
